stages:
  prepare:
    cmd: python src/create_features.py
    deps:
    - data/adult.data
    - data/adult.test
    - src/create_features.py
    params:
    - features.chi2percentile
    - features.train_path
    - features.test_path
    outs:
    - data/pipeline.pkl
    - data/processed_train_data.csv
    - data/processed_test_data.csv

  preprocess:
    cmd: python src/preprocessing.py
    deps:
    - data/Amazon_stock_data_2000_2025.csv
    - src/preprocessing.py
    outs:
    - data/processed_amazon_stock.csv
